server:
  port: 9191
  
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092 
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
#      retries: 3
#      batch-size: 16384
#      linger-ms: 1
#      buffer-memory: 33554432
#      acks: "all"
#        
